name: 'rsync-deploy'
description: 'Deploy using rsync over ssh with a key'
author: 'Matt Jones'
inputs:
  host:
    description: 'ssh remote host'
    required: true
  port:
    description: 'ssh remote port'
    default: 22
  username:
    description: 'ssh remote user'
    required: true
  group:
    description: 'ssh remote group'
    required: false
    default: 'web-dev'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
    required: true  
  source:
    description: 'source to copy from'
    required: true
  target:
    description: 'destination to deploy to on server'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'green'
