name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Upload Files
      uses: siva1024/scp-deployer@develop
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        pub: ${{ secrets.PUB }}
        source: "tests/a.txt"
        target: "~/"
    - name: Set up secret file
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        pub: ${{ secrets.PUB }}
        source: "tests/a.txt"
        target: "~/"
      run: |
        echo $key >> secrets.txt
        echo "" >> secrets.txt
        echo $pub >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
 
